name: Releases To Discord
author: Sillyangel
description: Automatically send a stylized Discord webhook of a GitHub Release description to a specified Discord channel.
inputs:
  webhook_url:
    description: Discord's webhook url. Use GH repo secrets.
    required: true
  color:
    description: Decimal color value for embed.
    required: false
    default: '2105893'
  username:
    description: String username for webhook.
    required: false
    default: 'Release Changelog'
  avatar_url:
    description: String url to webhook avatar picture.
    required: false
        default: ''
runs:
  using: 'node16'
  main: 'index.js'
branding:
  icon: file-text
  color: blue